"""Build the single hand-in notebook from the part notebooks.

Each of us works in our own notebooks in parts/. The first line of every cell names its lab step:

    code cells:      # STEP A4          or  # STANDIN B2
    Markdown cells:  <!-- STEP A4 -->   or  <!-- STANDIN B2 -->

This script reads parts/*.ipynb in name order, drops the STANDIN cells (stand-ins for another
person's step) and empty cells, sorts the rest by lab step (A0 ... A10, B1 ... B6, C1, C2,
D1 ... D5, then the extras X1 ... X5), keeps the notebook order inside one step, and writes
lab4_1_explaining_phishing_detectors.ipynb with a title cell. It then executes the notebook from
the repository root, so that it runs top to bottom exactly as the lab requires.

Usage (from anywhere, with the project environment active):
    python tools/assemble.py                # build and execute
    python tools/assemble.py --no-execute   # build only (quick check of markers and order)
    python tools/assemble.py --strict       # also fail if a lab step A0-D5 is missing (hand-in)
"""

import argparse
import re
import sys
import uuid
from pathlib import Path

import nbformat

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "lab4_1_explaining_phishing_detectors.ipynb"

# Lab order: A0 is the install cell, A1-A10, B1-B6, C1-C2 and D1-D5 are the lab's steps,
# X1-X5 are our optional extras and go at the end.
STEP_ORDER = (["A0"] + [f"A{i}" for i in range(1, 11)] + [f"B{i}" for i in range(1, 7)]
              + ["C1", "C2"] + [f"D{i}" for i in range(1, 6)] + [f"X{i}" for i in range(1, 6)])
LAB_STEPS = [s for s in STEP_ORDER if not s.startswith("X")]
RANK = {step: i for i, step in enumerate(STEP_ORDER)}

CODE_MARKER = re.compile(r"^#\s*(STEP|STANDIN)\b\s*(.*)$")
MD_MARKER = re.compile(r"^<!--\s*(STEP|STANDIN)\b\s*(.*?)\s*-->")

TITLE = """# Lab 4.1: Explaining Phishing Detectors

AI for Cybersecurity (D7084E / D7041E), Group 6
Kirill Silchenko (kirsil-5@student.ltu.se) and Stefanos Ntentopoulos (stente-5@student.ltu.se)

Parts A-D of the lab in order: train the detectors (supervised, semi-supervised, self-supervised),
explain them (glass boxes, SHAP, LIME), test the detector and the explanation (ablation, LIME
stability), and build a Belief Rule-Based expert system from the two most important features.
`random_state=42` throughout. Run from top to bottom; the dataset is `data/dataset_phishing.csv`
(or `dataset_phishing.csv` uploaded next to the notebook in Colab).

*Generated by `tools/assemble.py` from the notebooks in `parts/`. Do not edit this file by hand.*"""


class MarkerError(Exception):
    pass


def read_marker(cell):
    """Return (kind, argument) from the cell's first non-empty line; kind is STEP or STANDIN."""
    lines = [line.strip() for line in cell.source.splitlines() if line.strip()]
    if not lines:
        return None, None
    pattern = CODE_MARKER if cell.cell_type == "code" else MD_MARKER
    match = pattern.match(lines[0])
    if not match:
        return None, lines[0]
    return match.group(1), match.group(2).strip()


def collect(parts_dir):
    """Read every part notebook and return (sorted cells, problems, steps seen per file)."""
    kept, problems, sources = [], [], {}
    files = sorted(parts_dir.glob("*.ipynb"))
    if not files:
        raise MarkerError(f"no notebooks found in {parts_dir}")

    for file_no, path in enumerate(files):
        nb = nbformat.read(path, as_version=4)
        for cell_no, cell in enumerate(nb.cells, start=1):
            if cell.cell_type not in ("code", "markdown"):
                continue
            kind, arg = read_marker(cell)
            where = f"{path.name}, cell {cell_no}"
            if kind is None and arg is None:
                continue                                  # empty cell
            if kind is None:
                problems.append(f"{where}: no step marker; first line is: {arg[:70]!r}")
            elif kind == "STANDIN":
                continue                                  # the real step fills the gap
            elif arg not in RANK:
                problems.append(f"{where}: unknown step {arg!r} (expected one of A0-A10, "
                                f"B1-B6, C1-C2, D1-D5, X1-X5)")
            else:
                kept.append((RANK[arg], file_no, cell_no, cell))
                sources.setdefault(arg, set()).add(path.name)

    kept.sort(key=lambda item: item[:3])                 # step, then file, then position
    return [item[3] for item in kept], problems, sources


def clean(cell):
    """A copy of the cell without outputs, execution counts or old ids."""
    new = nbformat.from_dict(dict(cell))
    new["id"] = uuid.uuid4().hex[:8]                      # ids from different parts may clash
    new["metadata"] = {}
    if new.cell_type == "code":
        new["outputs"], new["execution_count"] = [], None
    return new


def build(cells):
    nb = nbformat.v4.new_notebook(metadata={
        "kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"},
        "language_info": {"name": "python"},
    })
    nb.cells = [nbformat.v4.new_markdown_cell(TITLE)] + [clean(c) for c in cells]
    nb.cells[0]["id"] = "title"
    return nb


def execute(nb, output):
    from nbconvert.preprocessors import CellExecutionError, ExecutePreprocessor

    runner = ExecutePreprocessor(timeout=3600, kernel_name="python3")
    try:
        runner.preprocess(nb, {"metadata": {"path": str(ROOT)}})
    except CellExecutionError as error:
        nbformat.write(nb, output)                        # keep the outputs up to the error
        print(f"\nExecution FAILED; the notebook with outputs up to the error is in {output.name}")
        print(str(error)[-1500:])
        return False
    nbformat.write(nb, output)
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--parts", type=Path, default=ROOT / "parts", help="folder with the part notebooks")
    parser.add_argument("--output", type=Path, default=OUTPUT, help="notebook to write")
    parser.add_argument("--no-execute", action="store_true", help="only build, do not run the notebook")
    parser.add_argument("--strict", action="store_true", help="fail if a lab step A0-D5 is missing")
    args = parser.parse_args()

    try:
        cells, problems, sources = collect(args.parts)
    except MarkerError as error:
        sys.exit(f"ERROR: {error}")
    if problems:
        print("ERROR: fix these cells first (every cell needs '# STEP <id>' or '# STANDIN <id>'):")
        print("\n".join(f"  - {p}" for p in problems))
        sys.exit(1)

    print("Steps found (step: part notebook):")
    for step in STEP_ORDER:
        if step in sources:
            print(f"  {step:4s} {', '.join(sorted(sources[step]))}")
    for step, files in sources.items():
        if len(files) > 1:
            print(f"WARNING: step {step} comes from more than one notebook: {', '.join(sorted(files))}")
    missing = [s for s in LAB_STEPS if s not in sources]
    if missing:
        print(f"Missing lab steps ({len(missing)}): {' '.join(missing)}")
        if args.strict:
            sys.exit("ERROR: --strict: every lab step A0-D5 must be present for the hand-in")

    nb = build(cells)
    nbformat.validate(nb)
    nbformat.write(nb, args.output)
    print(f"Wrote {args.output.relative_to(ROOT) if args.output.is_relative_to(ROOT) else args.output} "
          f"({len(nb.cells)} cells)")

    if args.no_execute:
        return
    print("Executing from the repository root ...")
    if not execute(nb, args.output):
        sys.exit(1)
    print("Executed top to bottom without errors.")


if __name__ == "__main__":
    main()
